version: '3'
services:
  db:
    build: ./db 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: ./app
    volumes:
      - ./app/static:/opt/app/static
      - ./app/media:/opt/app/media
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./nginx/html:/data/html:ro
      - ./app/static:/data/static
      - ./app/media:/data/media
    depends_on:
      - app
  es:
    image: elasticsearch:7.17.6
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - discovery.type=single-node
    ports:
      - 9200:9200
  pg_to_es:
    build: ./postgres_to_es
    depends_on:
      - db
      - es

volumes:
  pgdata:
  esdata: