version: '3'
services:
  es:
    image: elasticsearch:7.17.6
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  esdata: